version: '3'
services:
  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: always
    networks:
      - natbridge
  nodeapp:
    container_name: nodeapp
    restart: always
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/usr/src/app/uploads
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongodb/db
    networks:
      - natbridge
    ports:
      - ${API_PORT}:${API_PORT}
networks:
  natbridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
